SELECT ?rapero ?raperoLabel
WHERE {
  ?rapero wdt:P106 wd:Q2252262.
  OPTIONAL { 
    ?rapero wdt:P18 ?imagen.
    BIND(REPLACE(STR(?imagen), "http://commons.wikimedia.org/wiki/Special:FilePath/", "https://commons.wikimedia.org/wiki/Special:Redirect/file/") AS ?imagenUrl)
  }
  OPTIONAL { ?rapero wdt:${relacion} ?fecha_nac. }
  FILTER (!BOUND(?fecha_nac))
  SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en". }
}
LIMIT 10
